config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  devise_for :customers
  get 'films/index'
  get 'films/show'
  root 'home#index'
  resources :films, only: :show
  get '/search', to: 'search#index'
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id          :integer          not null, primary key
#  first_name  :string
#  last_name   :string
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Actor < ApplicationRecord
  has_many :film_actors
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id          :integer          not null, primary key
#  address     :string
#  address2    :string
#  district    :string
#  city_id     :integer
#  postal_code :string
#  phone       :string
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Address < ApplicationRecord
  belongs_to :city
  has_many :stores
  has_many :staffs
  has_one :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  has_one :film_category
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id          :integer          not null, primary key
#  name        :string
#  country_id  :integer
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class City < ApplicationRecord
  belongs_to :country
  has_many :addresses
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id          :integer          not null, primary key
#  name        :string
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Country < ApplicationRecord
  has_many :cities
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  store_id   :integer
#  first_name :string
#  last_name  :string
#  email      :string
#  address_id :integer
#  activebool :boolean
#  active     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :payments
  belongs_to :address
  belongs_to :store
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  release_year     :string
#  language_id      :integer
#  rental_duration  :integer
#  rental_rate      :float
#  length           :integer
#  replacement_cost :integer
#  special_features :text             is an Array
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Film < ApplicationRecord
  has_one :film_category
  has_many :inventories
  has_many :film_actors
  belongs_to :language
end

app/models/film_actor.rb
# == Schema Information
#
# Table name: film_actors
#
#  id          :integer          not null, primary key
#  actor_id    :integer
#  film_id     :integer
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class FilmActor < ApplicationRecord
  belongs_to :actor
  belongs_to :film
end

app/models/film_category.rb
# == Schema Information
#
# Table name: film_categories
#
#  id          :integer          not null, primary key
#  film_id     :integer
#  category_id :integer
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class FilmCategory < ApplicationRecord
  belongs_to :category
  belongs_to :film
end

app/models/inventory.rb
# == Schema Information
#
# Table name: inventories
#
#  id          :integer          not null, primary key
#  film_id     :integer
#  store_id    :integer
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Inventory < ApplicationRecord
  belongs_to :store
  belongs_to :film
  has_one :rental
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id          :integer          not null, primary key
#  name        :string
#  last_update :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Language < ApplicationRecord
  has_many :films
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id           :integer          not null, primary key
#  customer_id  :integer
#  staff_id     :integer
#  rental_id    :integer
#  amount       :float
#  payment_date :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :rental
  belongs_to :staff
end

app/models/rental.rb
# == Schema Information
#
# Table name: rentals
#
#  id           :integer          not null, primary key
#  rental_date  :datetime
#  inventory_id :integer
#  customer_id  :integer
#  return_date  :datetime
#  staff_id     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Rental < ApplicationRecord
  belongs_to :staff
  belongs_to :inventory
  belongs_to :customer
  has_many :payments
end

app/models/staff.rb
# == Schema Information
#
# Table name: staffs
#
#  id          :integer          not null, primary key
#  first_name  :string
#  last_name   :string
#  username    :string
#  password    :string
#  address_id  :integer
#  email       :string
#  store_id    :integer
#  active      :boolean
#  last_update :datetime
#  picture     :binary
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :store
  belongs_to :address
  has_many :rentals
  has_many :payments
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id               :integer          not null, primary key
#  manager_staff_id :integer
#  address_id       :integer
#  last_update      :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Store < ApplicationRecord
  belongs_to :address
  has_many :staffs
  has_many :inventories
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show]
  def index
    @films = Film.all.limit(100)
  end

  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_film
    @film = Film.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @most_released = Film.order(release_year: :desc).limit(5)
    @highest_rated = Film.order(rental_rate: :desc).limit(5)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @films = Film.where("title LIKE ?", "%#{params[:query]}%").limit(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
  require 'digest/md5'

  def film_image(film)
    color = Digest::MD5.hexdigest(film.title)[0..5]
    "https://dummyimage.com/300x300/#{color}/ffffff.png&text=#{film.title.gsub(' ', '+')}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/films/_film_cards.html.erb
<h1 class="header"><%= name %></h1>
<div class="ui divider"></div>
<div class="ui link cards film-cards">
  <% film_list.each do |film| %>
    <a class="card" href="<%= film_path(film) %>">
      <div class="image">
        <img src="<%= film_image(film) %>">
      </div>
      <div class="content">
        <div class="header"><%= film.title %></div>
        <div class="meta"><%= film.special_features.first %></div>
        <div class="description"><%= truncate film.description, length: 100, seperator: /\w+/ %></div>
      </div>
      <div class="extra content">
        <span class="right floated">
          <i class="star icon"></i> <%= film.rental_rate %>
        </span>
        <span>
          <i class="arrow alternate circle down outline icon"></i> <%= number_to_human film.rental_rate %>
        </span>
      </div>
    </a>
  <% end %>
</div>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Release date</th>
      <th>Description</th>
      <th>Rental Duration</th>
      <th>Release Year</th>
      <th>Replacement Cost</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.title %></td>
        <td><%= film.rental_rate %></td>
        <td><%= film.created_at %></td>
        <td><%= film.description %></td>
        <td><%= film.rental_duration %></td>
        <td><%= film.release_year %></td>
        <td><%= film.replacement_cost %></td>
        <td><%= film.language.name %></td>
        <td><%= link_to 'Show', film %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/films/show.html.erb
<div class="ui padded raised segment">
  <div class="ui items">
    <div class="item">
      <div class="image">
        <img src="<%= film_image(@film) %>">
      </div>
      <div class="content">
        <h1 class="header"><%= @film.title %></h1>
        <div class="meta">
          <span class="cinema">Price: <%= @film.rental_rate %></span>
        </div>
        <div class="meta">
          <span class="version">Version: <%= @film.replacement_cost %></span>
        </div>
        <div class="meta">
          <span class="release">Language: <%= @film.language.name %></span>
        </div>
        <div class="meta">
          <span class="release">Released: <%= @film.created_at.strftime("%F") %></span>
        </div>
        <div class="bottom aligned content">
          <button class="ui primary button">Download</button>
          <button class="ui primary button">Buy DVD</button>
          <button class="ui primary button">Rent</button>
        </div>
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <div class="ui five small statistics">
    <div class="statistic">
      <div class="value">
        <i class="small green arrow alternate circle up outline icon"></i> <%= number_to_human @film.length %>
      </div>
      <div class="label">
        Rented Time
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small green arrow alternate circle right outline icon"></i> <%= number_to_human @film.length %>
      </div>
      <div class="label">
        Buy DVD
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small green arrow alternate circle down outline icon"></i> <%= number_to_human @film.length %>
      </div>
      <div class="label">
        Download
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small yellow star icon"></i> <%= @film.rental_duration %>
      </div>
      <div class="label">
        Stars
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small users icon"></i> <%= number_with_delimiter @film.rental_duration %>
      </div>
      <div class="label">
        Ratings
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <h2 class="header">Description</h2>
  <div>
    <p><%= @film.description %></p>
  </div>
  <div class="ui divider"></div>
  <h2 class="header">Screenshots</h2>
  <div style="overflow-x: scroll; display: flex;">
    <img src="https://dummyimage.com/420x320/ff7f7f/333333.png&text=Sample 1" >
    <img src="https://dummyimage.com/420x320/7f7fff/333333.png&text=Sample 2" >
    <img src="https://dummyimage.com/420x320/7fff7f/333333.png&text=Sample 3" >
    <img src="https://dummyimage.com/420x320/7f7f7f/333333.png&text=Sample 4" >
  </div>
</div>